### ISSUE TITLE
GO MOD: rename package

### ISSUE THREAD

**Issue by alex-a-renoire** [stasBigunenko/monorepa#23]
Currently package name is "monorepa", but should be "github.com/stasBigunenko/monorepa"

**Comment by romanilchyshyn** [comment]
This change brakes available PRs and also requires to be "stop the world" i.e. no active development from all of team members.

As far as it not blocking, we can do later, when main functionality will be available.

**Comment by romanilchyshyn** [comment]
Also, as it is not a public dependency for other modules, it really doesn't matter if name has full path or not.
